---
# This role contains common plays that will run on all nodes
#
- name: Install common packages
  yum: name={{ item }} state=present
  with_items:
   - epel-release
   - logwatch
   - fail2ban
   - vim
   - debconf-utils


- name: upgrade all packages
  yum:
   name: '*'
   state: latest

- name: Install ntp
  yum: name=ntp state=present
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags: ntp

# work around RHEL 7, for now
- name: insert iptables template
  template: src=iptables.j2 dest=/etc/sysconfig/iptables
  notify: restart iptables

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false

- name: Set authorized key took from file
  authorized_key:
    user: huke
    state: present
    key: "{{ lookup('file', '/home/huke/.ssh/id_rsa.pub') }}"

- name: Set up Postfix to relay mail
  debconf: name=postfix
           question='{{ item.question }}'
           value='{{ item.value }}'
           vtype='{{ item.vtype }}'
  with_items:
    - { question: 'postfix/mailname', value: '{{ ansible_fqdn }}', vtype: 'string' }
    - { question: 'postfix/main_mailer_type', value: 'Internet Site', vtype: 'string' }

- name: Email log summary daily
  lineinfile: dest=/etc/cron.daily/00logwatch
              regexp="^/usr/sbin/logwatch"
              line="/usr/sbin/logwatch --output mail --mailto {{ Service_mail }} --detail high"
              state=present create=yes

- name: RSAAuth
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^RSAAuthentication"
              line="RSAAuthentication no"
              state=present
  notify: Restart ssh

- name: Pub key auth
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PubkeyAuthentication"
              line="PubkeyAuthentication yes"
              state=present
  notify: Restart ssh

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication yes"
              state=present
  notify: Restart ssh

- name: UsePAM yes
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^UsePAM"
              line="UsePAM yes"
              state=present
  notify: Restart ssh

- name: ChallengeRespo
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^ChallengeResponseAuthentication"
              line="ChallengeResponseAuthentication no"
              state=present
  notify: Restart ssh

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: Restart ssh
